name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Build Projects
        run: |
          cd server
          npm run build
          cd ../client
          npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/smmlove/htdocs/smmlove.pro
            source ~/.bashrc
            git pull
            cd server
            npm install
            npm run build
            cd ../client
            npm install
            npm run build
            pm2 reload all
